---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./beets/ks.yaml
  - ./cross-seed-jeopardy/ks.yaml
  - ./cross-seed/ks.yaml
  - ./dashbrr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./pinchflat/ks.yaml
  - ./plex-addons/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./tqm/ks.yaml
  - ./transmission/ks.yaml
  - ./varroa/ks.yaml
components:
  - ../../components/common
