---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./cilium.yaml
  - ./csi-driver-nfs.yaml
  - ./descheduler.yaml
  - ./emqx.yaml
  - ./external-dns.yaml
  - ./intel.yaml
  - ./itzg.yaml
  - ./meilisearch.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
