---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tandoor-test-secret
spec:
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .TANDOOR_SECRET_KEY }}"
        SOCIALACCOUNT_PROVIDERS: '{"openid_connect":{"SERVERS":[{"id": "authelia","name": "Authelia","server_url": "https://auth.franta.us/.well-known/openid-configuration","token_auth_method": "client_secret_basic","APP": {"client_id": "tandoor","secret": "{{ .TANDOOR_OAUTH_CLIENT_SECRET }}"}}]}}'

  dataFrom:
    - extract:
        key: /tandoor
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: akeyless-secret-store
